### ISSUE TITLE
No subtitles can be downloaded.

### ISSUE THREAD

**Issue by dusadvarshit** [xsthunder/download-youtube-subtitle#12]
I just downloaded the library from pip (June 16, 2021) and run test code.

All the test runs have proved to be a failure.

Youtube url: https://www.youtube.com/watch?v=CwUTLYIDZUY

This youtube url clearly has subtitles.

However running:
`dl-youtube-cc https://www.youtube.com/watch?v=CwUTLYIDZUY `
results in 
**Output:** zsh: no matches found: https://www.youtube.com/watch?v=CwUTLYIDZUY`

If I run 
`dl-youtube-cc "https://www.youtube.com/watch?v=CwUTLYIDZUY" ` Added extra quotes around string.
**Output:** `RR:  no caption available for this video ;( following are message from youtube
ERR:  []
ERR:  can't not retrive caption, visit  https://youtube.com/get_video_info?video_id=CwUTLYIDZUY  for detail
Traceback (most recent call last):
  File "/Users/dusadv/opt/anaconda3/envs/curieo_work/bin/dl-youtube-cc", line 8, in <module>
    sys.exit(fire_main())
  File "/Users/dusadv/opt/anaconda3/envs/curieo_work/lib/python3.6/site-packages/download_youtube_subtitle/main.py", line 322, in set_fire
    fire.Fire(fn)
  File "/Users/dusadv/opt/anaconda3/envs/curieo_work/lib/python3.6/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/dusadv/opt/anaconda3/envs/curieo_work/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/Users/dusadv/opt/anaconda3/envs/curieo_work/lib/python3.6/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/dusadv/opt/anaconda3/envs/curieo_work/lib/python3.6/site-packages/download_youtube_subtitle/main.py", line 248, in main
    captionTracks, title = get_tracks_title(data)
  File "/Users/dusadv/opt/anaconda3/envs/curieo_work/lib/python3.6/site-packages/download_youtube_subtitle/main.py", line 66, in get_tracks_title
    raise CaptionNotAvailableException()
download_youtube_subtitle.main.CaptionNotAvailableException`

I am not sure how to make it work.

**Comment by dusadvarshit** [comment]
I poked around the jupyter notebook and realized the function
`def get_data(link):
    data = requests.get(link)
    data = data.text
    return data`

is requesting url: https://youtube.com/get_video_info?video_id=CwUTLYIDZUY

However, this get_video_info doesn't return 404 error and no video information. I am not sure how this would work. 

<img width="1436" alt="Screenshot 2021-06-16 at 10 40 09 AM" src="https://user-images.githubusercontent.com/7974289/122161374-3af96480-ce8f-11eb-94d4-dc6ac63ca41d.png">

**Comment by xsthunder** [comment]
[use pytube to fetch video info, release ver2.0.0 by xsthunder · Pull Request #13 · xsthunder/download-youtube-subtitle](https://github.com/xsthunder/download-youtube-subtitle/pull/13)
