### ISSUE TITLE
KeyError: 'captions'

### ISSUE THREAD

**Issue by disonvon** [xsthunder/download-youtube-subtitle#14]
ERR:  can't not retrive caption,   for detail
Traceback (most recent call last):
  File "/root/.local/bin/dl-youtube-cc", line 8, in <module>
    sys.exit(fire_main())
  File "/root/.local/lib/python3.10/site-packages/download_youtube_subtitle/main.py", line 321, in set_fire
    fire.Fire(fn)
  File "/root/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/.local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/.local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/download_youtube_subtitle/main.py", line 243, in main
    captionTracks, title = get_tracks_title(videoID)
  File "/root/.local/lib/python3.10/site-packages/download_youtube_subtitle/main.py", line 28, in get_tracks_title
    return video_info["captions"]["playerCaptionsTracklistRenderer"]["captionTracks"], video_info["videoDetails"]["title"]
KeyError: 'captions'

**Comment by xsthunder** [comment]
Thanks for feedback! I'll try to fix it ASAP, but it's not guaranteed.

**Comment by xsthunder** [comment]
Thank you for waiting. fixed on version 3.0.2 please update the package or simply use the colab link. 

https://colab.research.google.com/drive/1oseD2yEsScx0YYOZ1x1F8GSG9iJ4x3qi?usp=sharing
