### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ptrstn** [xsthunder/download-youtube-subtitle#2]
Hello,

I was trying out your package and ran the example command provided:

```bash
 dl-youtube-cc 5tKOV0KqPlg --translation zh-Hans
```

Which returned:

```
INFO:  Available caption(s)(✔ marks chosen one, given by --caption_num in 0-index, default to 0):
INFO:  ✔ #0. .en      Englisch
INFO:  ⭕ #1. a.en     Englisch+(automatisch+erzeugt) automatically generated by youtube
Traceback (most recent call last):
  File "/home/why/so/nosy/venv/bin/dl-youtube-cc", line 8, in <module>
    sys.exit(fire_main())
  File "/home/why/so/nosy/venv/lib/python3.8/site-packages/download_youtube_subtitle/main.py", line 234, in set_fire
    fire.Fire(fn)
  File "/home/why/so/nosy/venv/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/why/so/nosy/venv/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/why/so/nosy/venv/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/why/so/nosy/venv/lib/python3.8/site-packages/download_youtube_subtitle/main.py", line 206, in main
    subtitle = merge_subtitle(subtitle, subtitle_cn)
  File "/home/why/so/nosy/venv/lib/python3.8/site-packages/download_youtube_subtitle/main.py", line 131, in merge_subtitle
    while sub['start'] != subtitle[slow_p]['start']:
IndexError: list index out of range
```

I am using ```Python 3.8.3``` and ```download-youtube-subtitle 0.1.2```

**Comment by ptrstn** [comment]
Looks like the command failed because the example video doesn't have Chinese subtitles (anymore?)

The command works with another video ID.

```bash
dl-youtube-cc yR0yo7Zaoks --translation zh-Hans
```

```
INFO:  Available caption(s)(✔ marks chosen one, given by --caption_num in 0-index, default to 0):
INFO:  ✔ #0. .zh-Hans Chinesisch+(Vereinfacht)
INFO:  ⭕ #1. .en      Englisch
INFO:  ⭕ #2. .fr      Französisch
INFO:  Save to  为什么外国人会觉得中国人不礼貌.txt
```

**Comment by xsthunder** [comment]
Hi, thanks for using my lib. 

I found out that this error occurs when the length of translation transcript list is greater than the original one. 

It seems that a update to my merge algorithm is needed. I will try to fix is in this weekend.

**Comment by xsthunder** [comment]
problem fixed by https://github.com/xsthunder/download-youtube-subtitle/releases/tag/v1.0.0

please try to reinstall by following
```
pip uninstall download-youtube-subtitle -y
pip install download-youtube-subtitle
```
